### PR TITLE
Recursive protection to _take_dump()

### LINKED ISSUE #411: Recusive issue with _take_dump()
**Describe the bug**
The _take_dump() function calls several functions in a specific order, which causes the _take_dump() function to be called again at the end of the sequence, creating a recursion problem. This occurs when trying to generate a drive dump of a faulty drive during startup.

**Expected behavior**
I have created a solution for this error, which involves implementing a counter to track the number of times the function is executed. Here is a clean and concise explanation of the solution:

I added a static variable called "recursive_counter" to keep track of the number of times the function is recursively called. This variable is initially set to 0 and is declared as "static" to retain its value across multiple function calls.

Before executing the function logic, I introduced a check using an "if" statement to compare the value of "recursive_counter" with a predefined constant called "MAX_TAKE_DUMP_ATTEMPTS." This constant represents the maximum number of allowed attempts for the function.

If the value of "recursive_counter" exceeds "MAX_TAKE_DUMP_ATTEMPTS," it means that the function has become recursive beyond the acceptable limit. In this case, a warning message is generated using the "ltfsmsg" function, indicating the number of recursive attempts made. Finally, the function returns 0 to indicate a failure or stop further recursive calls.

To prevent the recursive_counter from continuously incrementing, I increment it by one at the end of each function execution, just before the recursive call (if applicable).

By implementing this solution, we can control and limit the number of recursive calls in order to avoid the infinite recursion issue in the _take_dump() function.

### PR DESCRIPTION
**Pull request by ochomenosocho**
# Summary of changes

This pull request includes following changes or fixes. 

- Fix of issue #411
- Added a variable called `recursive_counter` to check how many times the function has been called.
- Added a new warning message to alert when this issue happens.

# Description

The _take_dump() function calls several functions in a specific order, which causes the _take_dump() function to be called again at the end of the sequence, creating a recursion problem. This occurs when trying to generate a drive dump of a faulty drive during startup.

Fixes #411

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have confirmed my fix is effective or that my feature works

### CODE REVIEW

File: src/tape_drivers/linux/sg/sg_tape.c [hunk 1]
```diff
@@ -392,6 +395,14 @@ static int _take_dump(struct sg_data *priv, bool capture_unforced)
 	time_t    now;
 	struct tm *tm_now;
 
+	/* To check if the function became recursive */
+	static unsigned char recursive_counter = 0;
```
Comment (piste-jp-ibm) [inline src/tape_drivers/linux/sg/sg_tape.c:399]: `static` variable is shared with all threads. So this is problematic when it is used in the multiple drive environment.

You need to use local variable or define this variable into `struct sg_data`.

**Review by piste-jp-ibm — CHANGES_REQUESTED** [review]

**Comment by ochomenosocho** [comment]
Hi, I added a `pthread_mutex` to  prevent errors when it is used in the multiple drive environment.

**Comment by piste-jp-ibm** [comment]
> I added a pthread_mutex to prevent errors when it is used in the multiple drive environment

No. It's not what I'm saying.. And the mutex you aded is no meaning at all.

The problem is sharing the `static unsigned char recursive_counter` variable in multiple drives in the multiple drive environment like LE.

The scenario below might happen.

1. We have 2 drives in one `ltfs` process, driveA and driveB
2. driveA and driveB is accessing to the each drives by their each `priv` and each thread concurrently (but function is shared, in other words, each thread could call the same function concurently)
3. A driveA thread calls `_take_dump()`
4. The driveA thread have a bad response, increment `recursive_counter` to 1 and call `_take_dump()` recursively
5. Context switch happens here and a driveB calls `_take_dump()`
6. The driveB thread see the `recursive_counter` and it is 1 because it is incremented to by step4 above. As a result, `_take_dump()`@driveB returns immediately without taking dump and `recursive_counter` is return to 0
7. Context switch happens here and back to the driveA thread
8. The driveA thread see the `recursive_counter` and it is 0 because it is reverted to by step6 above. As a result, `_take_dump()`@driveA calls `_take_dump()` recursively with incrementing `recursive_counter` to 1 again

So I cannot accept this kind of code.

File: src/tape_drivers/linux/sg/sg_tape.c [hunk 2]
```diff
@@ -53,6 +53,7 @@
 #include <unistd.h>
 #include <dirent.h>
 #include <sys/ioctl.h>
+#include <pthread.h>
```
Comment (piste-jp-ibm) [inline src/tape_drivers/linux/sg/sg_tape.c:56]: Shall be removed.

File: src/tape_drivers/linux/sg/sg_tape.c [hunk 3]
```diff
@@ -118,31 +121,25 @@ static inline int _parse_logPage(const unsigned char *logdata,
 								 const uint16_t param, uint32_t *param_size,
 								 unsigned char *buf, const size_t bufsize)
 {
-	uint16_t page_len, param_code, param_len;
-	uint32_t i;
+	const uint16_t page_len = ((uint16_t)logdata[2] << 8) | (uint8_t)logdata[3];
```
Comment (piste-jp-ibm) [inline src/tape_drivers/linux/sg/sg_tape.c:124]: Need to move to line 128.

And I cannot understand why you change the cast from `uint16_t` to `uint8_t`. Do you have a problem on the precious code?

File: src/tape_drivers/linux/sg/sg_tape.c [hunk 4]
```diff
@@ -118,31 +121,25 @@ static inline int _parse_logPage(const unsigned char *logdata,
...
+	uint32_t i = LOG_PAGE_HEADER_SIZE;
 	uint32_t ret = -EDEV_INTERNAL_ERROR;
 
-	page_len = ((uint16_t)logdata[2] << 8) + (uint16_t)logdata[3];
-	i = LOG_PAGE_HEADER_SIZE;
-
 	while(i < page_len)
 	{
-		param_code = ((uint16_t)logdata[i] << 8) + (uint16_t)logdata[i+1];
+		param_code = ((uint16_t)logdata[i] << 8) | (uint8_t)logdata[i+1];
```
Comment (piste-jp-ibm) [inline src/tape_drivers/linux/sg/sg_tape.c:131]: I cannot understand why you change the cast from uint16_t to uint8_t. Do you have a problem on the precious code?

I believe `param_code` is `uint16_t`, so both variables, `logdata[i]` and `logdata[i+1]` shall be casted to `uint16_t` explicitly.

File: src/tape_drivers/linux/sg/sg_tape.c [hunk 5]
```diff
@@ -118,31 +121,25 @@ static inline int _parse_logPage(const unsigned char *logdata,
...
-			if(bufsize < param_len){
-				memcpy(buf, &logdata[i + LOG_PAGE_PARAM_OFFSET], bufsize);
-				ret = -EDEV_INTERNAL_ERROR;
-				break;
-			} else {
-				memcpy(buf, &logdata[i + LOG_PAGE_PARAM_OFFSET], param_len);
-				ret = DEVICE_GOOD;
-				break;
-			}
+			const size_t copy_len = (bufsize < param_len) ? bufsize : param_len;
```
Comment (piste-jp-ibm) [inline src/tape_drivers/linux/sg/sg_tape.c:137]: I cannot accept this block. Why you need to evaluate `(bufsize < param_len)` twice in this block ?

Please revert.

File: src/tape_drivers/linux/sg/sg_tape.h [hunk 6]
```diff
@@ -82,6 +82,7 @@ struct sg_data {
 	struct timeout_tape  *timeouts;            /**< Timeout table */
 	struct tc_drive_info info;                 /**< Drive information */
 	FILE*                profiler;             /**< The file pointer for profiler */
+	uint8_t              recursive_counter;    /**< Recursive counter for take dump */
```
Comment (piste-jp-ibm) [inline src/tape_drivers/linux/sg/sg_tape.h:85]: `int` is my preference because there is no reason to use width defined integer.

File: .vscode/settings.json [hunk 7]
```diff
@@ -0,0 +1,6 @@
+{
```
Comment (piste-jp-ibm) [inline .vscode/settings.json:1]: Remove `.vscode` directory from the commit.

**Review by piste-jp-ibm — CHANGES_REQUESTED** [review]
Looks better. But we need to change more.

File: src/tape_drivers/linux/sg/sg_tape.c (hunk 4 above)
Comment (ochomenosocho) [reply src/tape_drivers/linux/sg/sg_tape.c:131]: Let's take a look to the original code.
```c
static inline int _parse_logPage(const unsigned char *logdata,
								 const uint16_t param, uint32_t *param_size,
								 unsigned char *buf, const size_t bufsize)
{
	uint16_t page_len, param_code, param_len;
	uint32_t i;
	uint32_t ret = -EDEV_INTERNAL_ERROR;

	page_len = ((uint16_t)logdata[2] << 8) + (uint16_t)logdata[3];
	i = LOG_PAGE_HEADER_SIZE;

	while(i < page_len)
	{
		param_code = ((uint16_t)logdata[i] << 8) + (uint16_t)logdata[i+1];
		param_len  = (uint16_t)logdata[i + LOG_PAGE_PARAMSIZE_OFFSET];
```

You are calling `logdata` as a `const unsigned char`, then all of the elements in that array are _8-bit_ (or _1 byte_) long. To me, the cast to `uint16_t` of the elements of `logdata[ ]` is totally *unnecessary*.

Let me explain my mind: If `page_len` is an `uint16_t` variable (_2 byte_ long), it can hold an `unsigned char` with a bitwise operation.

```c
page_len = (logdata[2] << 8) + logdata[3];
```

Let's assume the following:
```c
logdata[2] = 10001111;
logdata[3] = 00110011;
```

Then, the operation might look like this:
```c
page_len  = (0b10001111 << 8) | (0b00110011); 
                   // 10001111 00000

// then
page_len = 10001111 00110011;
```

With this being said, I only changed the cast to `uint8_t` in order to keep consistency with the code that you already developed. But in my opinion, the code should look like the following:

```c
static inline int _parse_logPage(const unsigned char *logdata,
								 const uint16_t param, uint32_t *param_size,
								 unsigned char *buf, const size_t bufsize)
{
	uint16_t page_len = (logdata[2] << 8) | logdata[3];
	uint16_t param_code, param_len;
	uint32_t i = LOG_PAGE_HEADER_SIZE;
	uint32_t ret = -EDEV_INTERNAL_ERROR;

	while(i < page_len)
	{
		param_code = (logdata[i] << 8) | logdata[i+1];
		param_len  = (uint16_t)logdata[i + LOG_PAGE_PARAMSIZE_OFFSET];
```

Comment (piste-jp-ibm) [reply src/tape_drivers/linux/sg/sg_tape.c:131]: No, you need to learn about C compiler and CPU more.

The point is the types `uintx_t` is not native types, but they are mapped to a correct native type by headers in `typedef` sentence. (see `stdint.h` on your system)

The code below is ambiguous because the computer cannot make a 'bit-wise OR' operation with different width variables, so `logdata[3]` is casted to `uint8_t (unsigned char)` and then implicitly casted to `unsigned short` (without `uint16_t`) in the `x86_64` architecture. Another behavior might be done in different architecture.

```C
((uint16_t)logdata[2] << 8) + (uint8_t)logdata[3];
```

In the previous code, this is clear description for C compiler.
```C
page_len = ((uint16_t)logdata[2] << 8) + (uint16_t)logdata[3];
```

Both `logdata[2]` and `logdata[3]` is casted to `uint16_t` first, make 'bit-wise OR' operation in 16-bit width and store the result to 16-bit wide page_len.

File: src/tape_drivers/linux/sg/sg_tape.h (hunk 6 above)
Comment (piste-jp-ibm) [reply src/tape_drivers/linux/sg/sg_tape.h:85]: Width defined integer must be used only for width defined field.

I believe there is no reason to fix this field as 8-bit wide. You need to use native data type, `char`, `short`, `int`, `long` or `long long`.

**Review by piste-jp-ibm — APPROVED** [review]
Looks good to me.

**Comment by piste-jp-ibm** [comment]
@juliocelon ,

Could you merge this with the `Squash and merge` button? Otherwise we might have so many meaningless commits in the `master` branch. 

Please be careful and please feel free to contact me if you are feeling uneasy. Let's have a live session and do it together.

**Review by perezle — COMMENTED** [review]
Hi Moises,  I do not understand the following change. 

```C
const uint16_t page_len = ((uint16_t)logdata[2] << 8) | (uint16_t)logdata[3];
	uint16_t param_code, param_len;
```
	
Why	`page_len` was defined as constant rather than a variable. 
	
	Thanks

**Comment by piste-jp-ibm** [comment]
@juliocelon ,

I think you need to `cherry-pick` the commit `a7916bf0b8d7264117341a5bcd06fb32a5c160f8@master` to the `v2.4-stable` branch.

**Comment by piste-jp-ibm** [comment]
> Hi Moises, I do not understand the following change.
> 
> ```c
> const uint16_t page_len = ((uint16_t)logdata[2] << 8) | (uint16_t)logdata[3];
> 	uint16_t param_code, param_len;
> ```
> 
> Why `page_len` was defined as constant rather than a variable.
> 
> Thanks

From language spec point of view, it just declares `page_len` is initialed by `((uint16_t)logdata[2] << 8) | (uint16_t)logdata[3]` and it is not changed at all in this function. In other words, the compiler report an error when it is changed by a fix in the future.

From logic point of view, there is no difference between `const` and non-`const` here. So it is not a bad definition. There is some side effects in this kind of declaration but I decided that it is good to respect the proposed code.
